### PR TITLE
Update state.md - Round #1

### PR DESCRIPTION
**Pull request by Berealady9**
This read too much like a bulleted list, so I tried to break some of that up, but there's probably still room for improvement so it reads better. I didn't see the video that goes with it in my files.

### CODE REVIEW

**Comment by MolloKhan** [comment]
Oh boy... somehow I screwed it up and ended up losing the video recording. Luckily it's just audio from my part because in this chapter I only explain things and I don't show anything on my screen. Let me know if you need me to re-record it anyways

Btw, the script looks great, thank you for making it much better

**Comment by MolloKhan** [comment]
All the code blocks that I want to show in the video are already in the script file

**Comment by Berealady9** [comment]
No worries. If there's nothing to really show on screen, then a re-recording probably isn't necessary. I can just create a file and animate the whole thing.

**Comment by MolloKhan** [comment]
Thanks!

**Pull request merged**
