### PR TITLE
Update state-coding.md - Round #1

### PR DESCRIPTION
**Pull request by Berealady9**
This was a longer one and there's quite a bit to cover. I reworded a lot to improve flow. Definitely make sure it's accurate. I also removed that link. I don't remember seeing links in past scripts I've worked on, so if that needs to be included, I'd ask Ryan or decide how you'd like to handle those going forward. My focus going through these is manly on what Kevin will say aloud.

I've also noticed that the script text varies quite a bit from what is said in the original recording, which can complicate things. Especially when a bunch of stuff is happening on the screen (maybe something repetitive) and you verbally walk through it in the recording, but omit that in the script text. If I don't add something back to the script to fill the void, then there's just a bunch of silence while very necessary coding is happening on the screen. I can only speed the video up so much before it's unintelligible (and, consequently, un-useful), so keep that in mind.

### CODE REVIEW

**Comment by MolloKhan** [comment]
> I also removed that link. I don't remember seeing links in past scripts I've worked on, so if that needs to be included, I'd ask Ryan or decide how you'd like to handle those going forward. My focus going through these is manly on what Kevin will say aloud.

If I recall correctly, we add a video note at the bottom showing a short link, but I don't know what service Ryan uses to shorten links, I'll ask

**Comment by MolloKhan** [comment]
> I've also noticed that the script text varies quite a bit from what is said in the original recording, which can complicate things. Especially when a bunch of stuff is happening on the screen (maybe something repetitive) and you verbally walk through it in the recording, but omit that in the script text. If I don't add something back to the script to fill the void, then there's just a bunch of silence while very necessary coding is happening on the screen. I can only speed the video up so much before it's unintelligible (and, consequently, un-useful), so keep that in mind.

Ok got it! Sorry about that, I need more practice :) - Do you think I should re-record a part of the video?

**Comment by MolloKhan** [comment]
Ok, I found how Ryan manages links, he uses bit.ly links. He adds them to the script and they're shown in the video as notes. Here's an example https://symfonycasts.com/screencast/blackfire/cache-compare?playAt=212

**Comment by Berealady9** [comment]
Gotcha! He must have added those in later.

**Comment by MolloKhan** [comment]
> Gotcha! He must have added those in later.

I added the link to the script. Could you please handle the note to the video?

**Pull request merged**
